name: "Home Assistant Discord Bot"
version: "v1.7.1"
slug: homeassistant-discord-bot
description: >-
  "The Home Assistant Discord Bot offers a pile of features designed to enhance your Discord experience by leveraging Home Assistant's capabilities via MQTT for lightweight communication and automatic setup of devices and entities."
arch:
  - amd64
  - aarch64
url: "https://github.com/kariudo/homeassistant-discord-bot-addon"
startup: services
image: ghcr.io/kariudo/homeassistant-discord-bot
init: false
services:
  - mqtt:want
options:
  BOT_TOKEN: ""
  MQTT_URL: "mqtt://localhost"
  MQTT_PORT: 1883
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  TOPIC_DISCOVERY: "homeassistant"
  TOPIC_BOT: "discordbot"
  GUILD_ID: ""
  YOUR_ID: ""
  BOT_ID: ""
  MQTT_CLIENT_ID: "discordbot_hass_1"
  BOT_ACTIVITY: "🏠 Watching the house"
  BOT_NICKNAME: "Caduceus"

schema:
  BOT_TOKEN: str
  MQTT_URL: str
  MQTT_PORT: int
  MQTT_USERNAME: str
  MQTT_PASSWORD: str
  TOPIC_DISCOVERY: str
  TOPIC_BOT: str
  GUILD_ID: str
  YOUR_ID: str
  BOT_ID: str
  MQTT_CLIENT_ID: str
  BOT_ACTIVITY: str
  BOT_NICKNAME: str
